import { afterAll, beforeAll, beforeEach, expect, it } from 'vitest';
import { db, pool } from '@/core/db/client';
import { migrateDatabase } from '@/core/db/migrate';
import { countQueries } from '@/core/db/query-log';
import { dayAt, addDays } from '@/core/time/tasks';
import { getSetting } from '@/core/db/settings-repo';
import { harness } from '@/modules/notes/tests/fixtures';
import { TaskCreate } from '@/modules/tasks/schema/validation';
import { NoteCreate, NoteListQuery } from '@/modules/notes/schema/validation';
import { TaskListQuery } from '@/modules/tasks/schema/validation';
import { createTask, patchTask, listTasks } from '@/modules/tasks/service';
import { createNote, listNotes } from '@/modules/notes/service';
import { CommitteeCreate, CommitteeListQuery } from '../schema/validation';
import { committeeCounts } from '../repo';
import * as service from '../service';
const run = harness.run;
const create = (name: string, scope: 'internal' | 'external' = 'internal') => run((ctx) => service.createCommittee(ctx, CommitteeCreate.parse({ name, scope })));
beforeAll(() => migrateDatabase());
beforeEach(() => harness.reset());
afterAll(() => pool().end());
it('COMM-B01 COMM-I01 COMM-A04 creates defaults and rejects case-insensitive duplicate names including restore', async () => {
  const item = await create('Finance');
  expect(item).toMatchObject({ name: 'Finance', scope: 'internal', status: 'active', revision: 1 });
  await expect(create('finance')).rejects.toMatchObject({ code: 'conflict', details: { fieldErrors: { name: ['COMM-I01'] } } });
  const removed = await run((ctx) => service.removeCommittee(ctx, item.id, item.revision));
  await create('Finance');
  await expect(run((ctx) => service.restoreCommittee(ctx, item.id, removed.opId))).rejects.toMatchObject({ code: 'conflict' });
});
it('COMM-B02 COMM-B05 COMM-A01 lists internal groups first and aggregates linked task counts without unrelated work', async () => {
  const external = await create('A external', 'external');
  const internal = await create('Z internal');
  const today = dayAt(await getSetting(db(), 'workspace.timezone'));
  await run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Overdue', committeeId: internal.id, dueDate: addDays(today, -1) })));
  await run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Other', committeeId: external.id })));
  const result = await run((ctx) => service.listCommittees(ctx, CommitteeListQuery.parse({ view: 'all' })));
  expect(result.data.map((row) => row.id)).toEqual([internal.id, external.id]);
  expect(result.data[0]?.stats).toEqual({ open: 1, completed: 0, overdue: 1, today: 0 });
  expect(result.meta.taskStats.open).toBe(2);
  expect((await run((ctx) => listTasks(ctx, TaskListQuery.parse({ committeeId: internal.id })))).data).toHaveLength(1);
  const queries = await countQueries(() => committeeCounts(db(), CommitteeListQuery.parse({}), today));
  expect(queries.queries).toBe(1);
});
it('COMM-B03 COMM-B06 COMM-A02 moving work updates both committee counts and filtered notes', async () => {
  const first = await create('First');
  const second = await create('Second');
  const task = await run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Action', committeeId: first.id })));
  await run((ctx) => patchTask(ctx, task.id, { revision: task.revision, committeeId: second.id }));
  expect((await run((ctx) => service.getCommittee(ctx, first.id))).stats.open).toBe(0);
  expect((await run((ctx) => service.getCommittee(ctx, second.id))).stats.open).toBe(1);
  const note = await run((ctx) => createNote(ctx, NoteCreate.parse({ title: 'Minutes', committeeId: second.id })));
  expect((await run((ctx) => listNotes(ctx, NoteListQuery.parse({ committeeId: second.id })))).data.map((row) => row.id)).toEqual([note.id]);
});
it('COMM-B04 COMM-I02 COMM-I03 COMM-A03 archive and trash preserve work and restore uses operation provenance', async () => {
  const item = await create('Preserve');
  const task = await run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Action', committeeId: item.id })));
  const archived = await run((ctx) => service.patchCommittee(ctx, item.id, { revision: 1, status: 'archived' }));
  await expect(run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Blocked', committeeId: item.id })))).rejects.toMatchObject({ code: 'rule_violation' });
  await run((ctx) => patchTask(ctx, task.id, { revision: task.revision, title: 'Still editable', committeeId: item.id }));
  const removed = await run((ctx) => service.removeCommittee(ctx, item.id, archived.revision));
  expect((await run((ctx) => listTasks(ctx, TaskListQuery.parse({ committeeId: item.id })))).data).toHaveLength(1);
  expect((await run((ctx) => service.restoreCommittee(ctx, item.id, removed.opId))).status).toBe('archived');
});
it('COMM-B03 COMM-A05 activity includes linked work and committee actions without unrelated entities', async () => {
  const item = await create('Activity');
  const task = await run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Action', committeeId: item.id })));
  const unrelated = await run((ctx) => createTask(ctx, TaskCreate.parse({ title: 'Other' })));
  await run((ctx) => service.patchCommittee(ctx, item.id, { revision: 1, status: 'archived' }));
  const entries = (await run((ctx) => service.activity(ctx, item.id))).data;
  expect(entries.some((row) => row.entityId === task.id && row.action === 'create')).toBe(true);
  expect(entries.some((row) => row.entityId === item.id && row.action === 'archive')).toBe(true);
  expect(entries.some((row) => row.entityId === unrelated.id)).toBe(false);
});
it('COMM-B04 manual reordering is revision-fenced and persists', async () => {
  const one = await create('One'); const two = await create('Two');
  await run((ctx) => service.reorderCommittees(ctx, { items: [{ id: two.id, revision: 1 }, { id: one.id, revision: 1 }] }));
  const result = await run((ctx) => service.listCommittees(ctx, CommitteeListQuery.parse({ sort: 'manual' })));
  expect(result.data.map((row) => row.id)).toEqual([two.id, one.id]);
  await expect(run((ctx) => service.patchCommittee(ctx, one.id, { revision: 1, name: 'Stale' }))).rejects.toMatchObject({ code: 'conflict' });
});
